apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ${{values.description}}
  labels:
    application: ${{values.application}}
    size: ${{values.size}}
    team: ${{values.owner}}
    environment: ${{values.environment}}
  name: ${{values.application}}-${{values.purpose}}